### ISSUE TITLE
[BUG] Miss fonts in Minecraft 1.18.1

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2666]
### Describe the bug

When play Minecraft 1.18.1, words will disappear.

### The log file and images/videos

[Log(pastebin)](https://pastebin.com/Q94WfTyF)
![Image](https://i.ibb.co/PGRgM5W/Screenshot-2022-02-03-17-30-04-287-net-kdt-pojavlaunch-debug.jpg)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install Java 17
3. Select virglrenderer
4. Start Minecraft 1.18.1
```

### Expected Behavior

Working right!

### Platform

```markdown
- Device model: Xiaomi Pad 5 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: from workflow build (commit fb7a4b2407145295ed52819911138b23095ecd2e)
```

**Comment by SprainedSpark89** [comment]
try reinstalling it

**Comment by ghost** [comment]
> try reinstalling it

looking the same

**Comment by SprainedSpark89** [comment]
does other render work

**Comment by ghost** [comment]
> does other render work

other render will crash with render error

**Comment by SprainedSpark89** [comment]
hey copy 1.18.1 jar to a different folder then rename the .jar to .zip then open it then check for en.json or english.json

**Comment by ghost** [comment]
> hey copy 1.18.1 jar to a different folder then rename the .jar to .zip then open it then check for en.json or english.json

only a version.json

**Comment by SprainedSpark89** [comment]
did you reinstall it?

**Comment by ghost** [comment]
> did you reinstall it?

yep

**Comment by SprainedSpark89** [comment]
huh

**Comment by SprainedSpark89** [comment]
delete the 1.18.1 folder then press play on 1.18.1

**Comment by ghost** [comment]
> delete the 1.18.1 folder then press play on 1.18.1

look the same

**Comment by SprainedSpark89** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2716 this may help

**Comment by ghost** [comment]
> #2716 this may help

I tried update to newest "action version" and don't see "VIRGL_TEXTURE_ID is not set" in debug log but it don't working :(

**Comment by SprainedSpark89** [comment]
'-'
go to versions then 1.18.1 then go to the file with .jar then copy it to downloads rename the .jar to .zip then go to assets minecraft lang see if there is a .lang or .json if there is then go back textures then font see if there .png files if so idk

**Comment by ONXOFF** [comment]
j'y comprend rien j'arrive pas a jouer en 1.17 et 1.18

**Comment by Mathias-Boulay** [comment]
The issue is fixed on the release candidate build.

**Comment by luigimannoni** [comment]
This same issue is back with 1.19 and virglrenderer, reinstalling does not work.

Along with text issues the renderer has quite fair problems in rendering transparency and some textures themselves, I am not using a custom resourcepack. Using custom resourcepacks also display the same problem.

![Screenshot_20220807-135257.jpg](https://user-images.githubusercontent.com/1405327/183291577-560718ae-5dc3-4349-9612-84fda53d6e4a.jpg)

![Screenshot_20220807-135405.jpg](https://user-images.githubusercontent.com/1405327/183291580-40d58f41-b6dd-4a3a-bcfc-95c86553c04a.jpg)

![Screenshot_20220807-135426.jpg](https://user-images.githubusercontent.com/1405327/183291593-d4294fd6-6acf-4c8d-b8c2-669c606e0048.jpg)

![Screenshot_20220807-135445.jpg](https://user-images.githubusercontent.com/1405327/183291601-fa31fd88-0405-4883-a233-9f2cdca66b0e.jpg)

**Comment by GaucovyAero** [comment]
> This same issue is back with 1.19 and virglrenderer, reinstalling does not work.
> 
> Along with text issues the renderer has quite fair problems in rendering transparency and some textures themselves, I am not using a custom resourcepack. Using custom resourcepacks also display the same problem.
> 
> ![Screenshot_20220807-135257.jpg](https://user-images.githubusercontent.com/1405327/183291577-560718ae-5dc3-4349-9612-84fda53d6e4a.jpg)
> 
> ![Screenshot_20220807-135405.jpg](https://user-images.githubusercontent.com/1405327/183291580-40d58f41-b6dd-4a3a-bcfc-95c86553c04a.jpg)
> 
> ![Screenshot_20220807-135426.jpg](https://user-images.githubusercontent.com/1405327/183291593-d4294fd6-6acf-4c8d-b8c2-669c606e0048.jpg)
> 
> ![Screenshot_20220807-135445.jpg](https://user-images.githubusercontent.com/1405327/183291601-fa31fd88-0405-4883-a233-9f2cdca66b0e.jpg)

if you don't have a snapdragon 8xx cpu, it's very likely that virgl will not work correctly (because of bad gpu precision and extension support on your side)

**Comment by luigimannoni** [comment]
Oh, this is coming from an OnePlus 6T/Android 11/Latest play store Pojavlauncher. Certainly it has a Snapdragon 845 cpu.

**Comment by GaucovyAero** [comment]
> Oh, this is coming from an OnePlus 6T/Android 11/Latest play store Pojavlauncher. Certainly it has a Snapdragon 845 cpu.

you probably need an even higher snapdragon 8xx model then, verified working with an 870.

**Comment by maj113** [comment]
> > Oh, this is coming from an OnePlus 6T/Android 11/Latest play store Pojavlauncher. Certainly it has a Snapdragon 845 cpu.
> 
> you probably need an even higher snapdragon 8xx model then, verified working with an 870.

Can confirm working with 8g1 too

**Comment by Syclusion** [comment]
> > Oh, this is coming from an OnePlus 6T/Android 11/Latest play store Pojavlauncher. Certainly it has a Snapdragon 845 cpu.
> 
> you probably need an even higher snapdragon 8xx model then, verified working with an 870.

I have an 888 with the same problem. Maybe its manufacturer related?
