### ISSUE TITLE
[BUG] game closed/crashes when loading  1.12.2 or below

### ISSUE THREAD

**Issue by AGENTISNUM1** [PojavLauncherTeam/PojavLauncher#3319]
### Describe the bug

There is no crash pop up or log.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8835637/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start pojav launcher and load up forge version 1.12.2 (14.23.5.2859) with or without mods. 1.7.10 version does the same.

Wait a bit...

Game will close before or on the main menu screen. Relaunching will NOT provide a crashlog. I have switched the renderer and the jre and it does not work.
```

### Expected Behavior

I expect to be able to play the game normally and have it launch.

### Platform

```markdown
- Device model:Chromebook (Version 101.0.4951.72 (Official Build) (32-bit))
- CPU architecture: 
- Android version: 
- PojavLauncher version: latest
```

**Comment by Mathias-Boulay** [comment]
"latest" is not a version
upload the latestlog file, too

**Comment by Mathias-Boulay** [comment]
oh wait, arm32.
Yeah, the unpacker had an issue, it has been fixed today. Check gplay for an update (again)

**Comment by AGENTISNUM1** [comment]
Updated. Still doesn't work. 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8835890/latestlog.txt)

**Comment by AGENTISNUM1** [comment]
Im gonna try hard reinstall.

**Comment by Mathias-Boulay** [comment]
may be needed, given the log
`[21:49:21] [Client thread/ERROR]: There was a problem reading the entry META-INF/versions/9/module-info.class in the jar /storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-glfw-classes.jar - probably a corrupt zip
cpw.mods.fml.common.LoaderException: java.lang.IllegalArgumentException`

**Comment by AGENTISNUM1** [comment]
It crashed and gave me this... 
[hs_err_pid17245.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8835949/hs_err_pid17245.log)

**Comment by AGENTISNUM1** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8835964/latestlog.txt)

**Comment by AGENTISNUM1** [comment]
nvm its not just forge its all versions

**Comment by AGENTISNUM1** [comment]
everything below 1.13

**Comment by Mathias-Boulay** [comment]
I bet 100% the unpacker, but I don't have devices to test this.

**Comment by AGENTISNUM1** [comment]
Ok so i just chill and play 1.13+?

**Comment by Mathias-Boulay** [comment]
I guess...
Can I get a log of a vanilla version crashing ?

**Comment by AGENTISNUM1** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8836103/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Thanks

**Comment by AGENTISNUM1** [comment]
Ok thanks for the help

**Comment by AGENTISNUM1** [comment]
I can confirm i am loading forge 1.16.5 with 50+ mods fine, so its definitely a pre-1.13 issue.

**Comment by AGENTISNUM1** [comment]
Solution found: If i don't tab out of the game while it is loading, it will not crash.

**Comment by AGENTISNUM1** [comment]
This was fixed in the latest gplay update. Thank you so much @Mathias-Boulay.
