### ISSUE TITLE
[BUG] [Custom controls] Symbols sometimes disappear

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#3758]
### Describe the bug

**Description**
I have noticed for a long time that when importing controls, Pojav sometimes breaks the display of some control symbols. This can occur both visually (the data in the file remains the same) as well as with file corruption (the symbol will be replaced with ��).

### The log file and images/videos
Demo:
https://youtu.be/HNSMKbELYyc

### Steps To Reproduce

Just import my controls and see the error.

### Platform

```markdown
- Device model: Tecno Pova 2
- CPU architecture: x64
- Android version: 11
- PojavLauncher version: latest from actions
```

### Anything else?

My controls:
https://www.mediafire.com/download/bxxp1jcf24qrih5 (sry, github can't upload it)

**Comment by Mathias-Boulay** [comment]
The problem seem to be occuring upon the decoding stage

**Comment by GaucovyAero** [comment]
> The problem seem to be occuring upon the decoding stage

thing is this also happens on controlmaps that are already there, not just imported ones, its also very random

**Comment by Mathias-Boulay** [comment]
The issue was fixed on the following build: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/4010379482, I can now import your controlmap without the issue.
Thank you for the clean reporting by the way, I couldn't have asked for better

**Comment by Felix14-v2** [comment]
Thanks! I'll check it tomorrow with my other controlmaps

**Comment by Felix14-v2** [comment]
@Mathias-Boulay , it looks like this is only partially fixed:
https://youtu.be/XBFz2uR0R6E
https://youtu.be/gJ5Xz1q8SU8

**Comment by Mathias-Boulay** [comment]
Huuu, that's indeed weird, let me check

**Comment by Mathias-Boulay** [comment]
Should be fixed now

**Comment by Felix14-v2** [comment]
I can confirm, now I don't find any related problems, thank you so much!
