### ISSUE TITLE
(BUG) crashs on lauch hp chromebook from 2022

### ISSUE THREAD

**Issue by Xcite8** [PojavLauncherTeam/PojavLauncher#4327]
### Describe the bug

im useing my chromebook from 2022 i reset a lot it can run mc launcher and tlauncher but i wanna use pojav and its crashing on launch

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11932013/latestlog.txt)

### Steps To Reproduce

```markdown
idk what to type here
```

### Expected Behavior

launch pojav clicked play i tryed every verison it crashed

### Platform

```markdown
- Device model: HQ-TR 71025
- CPU architecture: idk
- Android version: android 12 chrome OS
- PojavLauncher version: latest
```

### Anything else?

nothing

**Comment by Xcite8** [comment]
please help

**Comment by ghost** [comment]
oh yea. i experienced this issue before.
use [this](https://github.com/ffha/android-openjdk-build-multiarch/suites/13850277213/artifacts/769319713) runtime to fix it. To use the runtime, open the zip and go to the settings in pojav launcher, then the Java settings. Import the runtime, and you should be good to go.
Tell me if you need me to give you screenshots to show you.

**Comment by GaucovyAero** [comment]
> oh yea. i experienced this issue before. use [this](https://github.com/ffha/android-openjdk-build-multiarch/suites/13850277213/artifacts/769319713) runtime to fix it. To use the runtime, open the zip and go to the settings in pojav launcher, then the Java settings. Import the runtime, and you should be good to go. Tell me if you need me to give you screenshots to show you.

this is a dead link tho, but it is indeed fixed in the latest android-openjdk-build-multiarch actions

**Comment by ghost** [comment]
[hs_err_pid14143.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/12330716/hs_err_pid14143.log)
apparently still crashes on latest commit, heres jre log

**Comment by ma821** [comment]
You guys are helping my 8 year old reset his brothers chromebook

**Comment by ma821** [comment]
??
