### ISSUE TITLE
[FABRIC MINECRAFT CRASH] Crash on joining my server

### ISSUE THREAD

**Issue by Morizera** [PojavLauncherTeam/PojavLauncher#4772]
### Describe the bug

Running a fabric modded minecraft in 1.20.1

Game forcibly closes when joining my server.

### The log file and images/videos

---- Minecraft Crash Report ----
Lasted log: https://mclo.gs/uDtBwK0

**Comment by GaucovyAero** [comment]
send the whole latestlog.txt file (please the file, not whats in it)

**Comment by Morizera** [comment]
> send the whole latestlog.txt file (please the file, not whats in it)

Done, sorry for being inexperienced

**Comment by GaucovyAero** [comment]
still wrong log btw, np
android 9 and lower: /storage/emulated/0/games/PojavLauncher/latestlog.txt
android 10 and higher: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/latestlog.txt
you can access/send the file with zarchiver

**Comment by Morizera** [comment]
Mine isn't pojav, is launcher on pc... Idk why is saying on the post it is pojav. but anyway, I swear to you that this archive is the latest log of mine

**Comment by GaucovyAero** [comment]
no support then, try removing some mods and see if that fixes it, cant really tell you much more than that

**Comment by Morizera** [comment]
No support because need an official mojang account or something like that? I just don't understand

**Comment by Morizera** [comment]
OH, I'm inside pojav github... sorry man for wasting your time man

**Comment by Morizera** [comment]
Not totally wrong btw, because I'm just doing all of this to play with my friend, and he utilizies pojav... so my server is configured to work only with mods compatible with pojav... but anyway, I'm facing a problem that doesn't refer to pojav itself, so my sorry man

**Comment by GaucovyAero** [comment]
> Not totally wrong btw, because I'm just doing all of this to play with my friend, and he utilizies pojav... so my server is configured to work only with mods compatible with pojav... but anyway, I'm facing a problem that doesn't refer to pojav itself, so my sorry man

np, if i actually knew whats the issue i would have told you

**Comment by Morizera** [comment]
I've tried moving all serverside mods to my client and... it worked... but I don't wanna play pojav with 150 server side mods xd

**Comment by GaucovyAero** [comment]
nice

**Comment by Morizera** [comment]
Trying to solve... I think there is a obligatory mod in the serverside folder that I need to use in client... but the game doesn't tell me what is

**Comment by Morizera** [comment]
My gf have a poco m5s.. I think the chipset is an Helio G95 MediaTek and the gpu is Mali-G76 MC4... do u think it will run in 1.20.1 with vulkan mod patched and some vanilla friendly mods?

**Comment by Morizera** [comment]
Ha! Found the problem: [10:00:30 WARN]: Failed to create invalid feature betterendisland:pillar_initial_11
[10:00:30 ERROR]: Unable to place top spike at class_2338{x=-19, y=60, z=59}. This shouldn't happen!
Lets try removing some mods

**Comment by GaucovyAero** [comment]
nice
