### ISSUE TITLE
[BUG] Single tap is perceived as double tap

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#5633]
### Description

After updating to https://github.com/PojavLauncherTeam/PojavLauncher/commit/3443b049b646c7c6f3d08b4a3d33f044daa86330 the launcher perceives each single tap as a double tap unless you hold your finger for a second or longer. This essentially makes the game menus unusable

### Demo

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/3f759b4e-80d0-42da-a40a-1bb741009e69

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/dada4619-de9a-417c-b84b-e64bb72a978e

### To Reproduce

```markdown
1. Install the latest v3_openjdk build from Actions
2. Launch Minecraft (tested with MC 1.20.4-1.21
3. Try to press a button with a button behind it on nested screen, a boolean setting or a world
4. See the game receiving double tap instead of a single one
```

### Expected Behavior

Touch behavior should be as it was in previous builds 

### Info

```markdown
- Device: Tecno Pova 2
- CPU: arm64
- Android: 11
- PojavLauncher: edelweiss-20240618-856bace-v3_openjdk
```

### Additional

https://github.com/PojavLauncherTeam/PojavLauncher/commit/85a9f217e59fae42deb9cc3746d2caef28eb9bb0 was the last commit without this bug. Also the bug affects only menus, in a world everything works as it should.

**Comment by Mathias-Boulay** [comment]
outdated build. Update, fixed by https://github.com/PojavLauncherTeam/PojavLauncher/commit/b03bb6298e41ea377c6e65087a6c392c82635e21

**Comment by Felix14-v2** [comment]
> outdated build. Update, fixed by [b03bb62](https://github.com/PojavLauncherTeam/PojavLauncher/commit/b03bb6298e41ea377c6e65087a6c392c82635e21)

I tested the latest v3_openjdk build from actions (which contains this commit), the bug is still there. I specified the launcher version above:

> PojavLauncher: edelweiss-20240618-856bace-v3_openjdk

**Comment by Felix14-v2** [comment]
By the way, the commit you mentioned doesn't support 1.21, but as you can see, the demo video was recorded on Minecraft 1.21. If you still don't believe, here's the video with the launcher version in it:

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/e4b682a8-eff5-4493-829b-422a103812b1

**Comment by Mathias-Boulay** [comment]
fixed
